[package]
name = "image_triangulator"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.25.1"
ndarray = "0.15.6"
delaunator = "1.0.2"
rand = "0.8.5"
plotters = "0.3.6"
clap = { version = "4.5.10", features = ["derive"] }
