[package]
name = "image_triangulator"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.31", features = ["cargo"] }
delaunator = "1.0.2"
image = "0.25.5"
ndarray = "0.16.1"
ndarray-conv = "0.4.1"
rand = "0.9.0"
